labels:
  time:
    - "Time: <1 Hour"
    - "Time: <2 Hours"
    - "Time: <4 Hours"
    - "Time: <1 Day"
    - "Time: <1 Week"
    - "Time: <1 Month"
  priority:
    - "Priority: 1 (Normal)"
    - "Priority: 2 (Medium)"
    - "Priority: 3 (High)"
    - "Priority: 4 (Urgent)"
    - "Priority: 5 (Emergency)"
